VERSION 0.7
FROM node:lts
RUN apt-get update && apt-get upgrade -y

deps:
  COPY package.json yarn.lock ./
  RUN yarn install --frozen-lockfile --non-interactive
  COPY tsconfig.json ./
  COPY app app

build:
  FROM +deps
  ENV NODE_ENV=production
  RUN yarn build
  SAVE ARTIFACT dist /dist AS LOCAL dist
